swagger: '2.0'

# This is your document metadata
info:
  version: 1.0.0
  title: Webfinger
  x-protocol: org.ietf.webfinger
  description: |
    Implements a [Webfinger](https://tools.ietf.org/html/rfc7033) service.

    An ```acctUri``` contains of a local account identifier and the hostname of the system.
    An ```acctUri``` that has a different hostname in the host-section MUST be rejected.

    All user parts of ```acctUris``` are contextualised, that means that no user part links to
    actual user accounts.
tags:
  -
    name: Identity
  -
    name: Webfinger

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Returns the a webfinger query response.

        An LMS webfinger MUST respond to acctUris. It MAY allow to verify the author of a resource.
        This could be used to verify a XAPI result URL and the actor.

        For authorised requests this also includes ```links``` to additional resources.

        For authorised requests that are linked to the same context as the ```resource``` this will also
        include ```aliases``` that cover all alias acctUris are used in overlapping or sub-contexts.

        Unauthorized requests just receive the subject information.
      # This is array of GET operation parameters:
      operationId: getResource
      produces:
        - application/json
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
        404:
          description: Resource is not found in the registry
      parameters:
        - name: resource
          in: query
          description: |
            the webfinger acct uri to test
          type: string
          required: true
        - name: rel
          in: query
          description: |
            limit the resulting relations relation type. Multiple occurences possible.
          type: string
  /rel:
    get:
      description: |
        Returns possible relations of the registry.
      # This is array of GET operation parameters:
      operationId: getRelations
      responses:
        # Response code
        200:
          description: Successful Create response
  /profile:
    put:
      description: |
        Adds a new ```acctUri``` to the registry.

        The PowerTLA Webfinger service requires for all acctUris an account context that is a
        XAPI context or registration. Consequently, a request requires 
        an object containing a registration key, a XAPI context object, or both.

        This is primarily used for front-end resources that create sub-contexts for external services
        and resource providers.

        A new ```acctUri``` can be only added to a new context for the same user. If
        a new ```acctUri``` is requested for an already existing context, a ```conflict```
        will get reported.
      operationId: addAccount
      consumes:
        - application/json
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful Create response, returning an ```{"subject": acctUri}``` object
        409:
          description: the account already exists for the context/registration
  /profile/{acctUri}:
    get:
      description: |
        Returns the a user profile.

        This will return the full profile and preferences for authorized users.

        For users sharing the same context as the profile will see core details, but no user preferences.
        The available profile information might be restricted by the system's ACL.

        Users outside the context will receive a confirmation that the profile exists.

        Unauthorised requests are ```Forbidden```.
      # This is array of GET operation parameters:
      operationId: getProfilePage
      produces:
        - application/json
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
        204:
          description: Successful response for profile confirmation outside of the context
        404:
          description: acctUri is not found in the registry
      parameters:
        - name: acctUri
          in: path
          description: |
            the webfinger acct-uri to test. The acctUri MUST be percent encoded, as per
            [Section 2.1 of RFC3986](https://tools.ietf.org/html/rfc3986#section-2.1).
          type: string
          required: true
    put:
      description: |
        Add a new resource to the ```acctUri``` in the registry.

        This operation might be used to add external (potentially short lived)
        resource object (e.g. a WIKI) to an account profile. This can help
        identifying who has been working on a resource.

        A resource must already exists in the same context as the acctUri.

        One resource might be added to serveral accounts.
      operationId: addAccountResource
      consumes:
        - application/json
      # Expected responses for this operation:
      responses:
        # Response code
        201:
          description: Successful Create response
        404:
          description: acctUri is not found in the registry
        409:
          description: the provided resource Uri exists outside of the acctUri context.
      parameters:
        - name: acctUri
          in: path
          description: |
            the webfinger acct-uri to test. The acctUri MUST be percent encoded, as per
            [Section 2.1 of RFC3986](https://tools.ietf.org/html/rfc3986#section-2.1).
          type: string
          required: true
